### ISSUE TITLE
How to change durable as True for the queue using env or code?

### ISSUE THREAD

**Issue by sureshnepolian** [rabbitmq/rabbitmq-perf-test-for-cf#13]
I need to test in an enviroment where queues already exists with durable=true, is there any option here where we can set queue durable as true in the env variable or if not how can we declare it in the code?

 channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=precondition_failed - inequivalent arg 'durable' for queue 'this-is-incoming_queue' in vhost 'xxxxxxxx-ac66-48a0-8b6a-xxxxxxxx': received 'false' but current is 'true', class-id=50, method-id=10)

**Comment by acogoluegnes** [comment]
You can use the `-f` (for `flag`) option as [stated in the documentation](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#basic-usage):

```
bin/runjava com.rabbitmq.perf.PerfTest -x 1 -y 2 -u "throughput-test-5" --id "test-5" -f persistent
```

From the error you get, the `this-is-incoming_queue` already exists but has been created with different parameters than those PerfTest are using to create it. You can try to delete the queue before running PerfTest (if it does not contain any sensitive data).

**Comment by sureshnepolian** [comment]
Thank you! it worked.  Was in great confusion between durable flag as persistent flag. was tried using durable flag instead of persistent which is also creates durable flag at rabitmq automatically.
